### ISSUE TITLE
[Feature Request]: Adding multi language support system✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Soujanya2004/wanderlust-2024#122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add multi language support system to the website which can help us understand in their native language.
@Soujanya2004 can you assign me this issue.

### Priority
High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@T-Rahul-prabhu-38 progress?

**Comment by dipexplorer** [comment]
@Soujanya2004 , 

Could u assign this to me?

**Comment by Soujanya2004** [comment]
@T-Rahul-prabhu-38 its been more than a week after assigning and no progress so assigning others

**Comment by Suvadip-sana** [comment]
@Soujanya2004   Assigned it to me Please,

**Comment by Soujanya2004** [comment]
@dipexplorer progress?

**Comment by dipexplorer** [comment]
@Soujanya2004, assign this to @Suvadip-sana

**Comment by Suvadip-sana** [comment]
@Soujanya2004  Assign it to me.

**Comment by Suvadip-sana** [comment]
@Soujanya2004 
![image](https://github.com/user-attachments/assets/630601ef-d8f5-47a9-a89b-0b142d129623)
Is this position ok with tthat?  I amke it fixed. Like chatbot in left bottom corner. So that it can be accessable from any page and any time.  What your thought?

**Comment by Suvadip-sana** [comment]
@Soujanya2004 
In small screen
![image](https://github.com/user-attachments/assets/3c679aed-32d1-478f-bba5-88b2cefa36ba)

**Comment by Soujanya2004** [comment]
after togler

**Comment by Suvadip-sana** [comment]
@Soujanya2004 But then it's ISSUE with the responsiveness. And also need to add it for mobile screen also, because for now the desktop nav and mob-nav is different.  Although it's up to you.

**Comment by Suvadip-sana** [comment]
@Soujanya2004 

Sorry but here is an problem. It's come with by default styling in which platform i used. That is `gtranslate` So it has 5 option of display that is top left, top right, bottom left, bottom right and inline.  The first 4 option is not working for your preferable position. So i try inline option but it destroy whole website structure along with it's own by default style.   Here it's screenshot -->
![image](https://github.com/user-attachments/assets/9b7c3c0e-f7d3-4598-8597-f916f018ac20)

But in this. I customely changes it's size and padding along with dark mode and normal mode. I don't think any problem arise because of this -->

https://github.com/user-attachments/assets/644b85e5-43b2-47dc-b73a-5dd3b33cf81b

**Comment by Suvadip-sana** [comment]
https://github.com/user-attachments/assets/2070ba8c-ab17-4c3e-9158-258f439a2e4c

**Comment by Suvadip-sana** [comment]
@Soujanya2004  If your concern is about it's visibility. Then I should make it's color them red color like chatbot color. Sorry but it's  UI is changeable but position not, also if it supposed to be, I did not figure it out.

**Comment by Soujanya2004** [comment]
@Suvadip-sana no issues let it be at the bottom 
U can change the colour according to website theme

**Comment by Suvadip-sana** [comment]
@Soujanya2004  Thanks. I create a PR of this.
