### ISSUE TITLE
[Feature Request]: Give access to admin

### ISSUE THREAD

**Issue by Soujanya2004** [Soujanya2004/wanderlust-2024#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Admin should have access over all the listing and reviews i.e they can edit delete or add any listing
I will be sharing username and password of the admin which should be given access to entire website as owner, whenever the user is logged in with that username and password, all access should be permitted (owner of all listing created on the website)

### Use Case

Main access should be given to developer/admin in case of faulty usage of website

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment]
@dipexplorer yes, as soon as the admin login display hello admin in the navbar

**Comment by Soujanya2004** [comment]
@dipexplorer  progress?

**Comment by dipexplorer** [comment]
Dear @Soujanya2004 

My midterm exams are currently ongoing, and due to this, I'm facing some challenges in managing all the issues at once. I some more days to complete the proper implementation for the admin interface. I appreciate your understanding and patience.

**Comment by dipexplorer** [comment]
Dear @Soujanya2004 

Unfortunately, due to my ongoing midterm exams, I'm facing difficulty managing this larger issue within the current timeframe. If this task is urgent, please feel free to assign it to someone who is available and interested in taking it up right away. I completely understand the importance of keeping the project moving smoothly, and I apologize for any inconvenience caused.

However, if no one is able to take over the task, I will certainly be able to resume work and complete the implementation within a few days.

**Comment by Soujanya2004** [comment]
@dipexplorer I too understand that, the contribution period is nearly coming to end (only 7 days left) make sure you complete the small tasks, the level 3 task i can pause for 3 days

**Comment by Soujanya2004** [comment]
@dipexplorer pull the code once and check, i reviewed that
